find_package(Doxygen REQUIRED dot mscgen dia)

set(DOXYGEN_CALLER_GRAPH ON)
set(DOXYGEN_CALL_GRAPH ON)
set(DOXYGEN_EXTRACT_ALL ON)
set(DOXYGEN_GENERATE_TAGFILE ON)
set(DOXYGEN_ENABLE_PREPROCESSING ON)
set(DOXYGEN_MACRO_EXPANSION ON)

set(DOXYGEN_GENERATE_HTML NO)
set(DOXYGEN_GENERATE_XML YES)

doxygen_add_docs(${PROJECT_NAME}-docs ${PROJECT_SOURCE_DIR})
