message(STATUS "Compilation with STDPeriph library")

set(STDPERIPH_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/stdPeriph")
set(STDPERIPH_INCLUDE_DIR "${STDPERIPH_ROOT_DIR}/include")
set(STDPERIPH_SOURCE_DIR "${STDPERIPH_ROOT_DIR}/src")

include_directories(${STDPERIPH_ROOT_DIR}/include)

set(MISK				"${STDPERIPH_SOURCE_DIR}/misc.c")
set(ADC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_adc.c")
set(CAN				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_can.c")
set(CEC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_cec.c")
set(CRC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_crc.c")
set(CRYP				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_cryp.c")
set(CRYP_AES		"${STDPERIPH_SOURCE_DIR}/stm32f4xx_cryp_aes.c")
set(CRYP_DES		"${STDPERIPH_SOURCE_DIR}/stm32f4xx_cryp_des.c")
set(CRYP_TDES		"${STDPERIPH_SOURCE_DIR}/stm32f4xx_cryp_tdes.c")
set(DAC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dac.c")
set(DBGMCU			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dbgmcu.c")
set(DCMI				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dcmi.c")
set(DFSDM			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dfsdm.c")
set(DMA				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dma.c")
set(DMA2D			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dma2d.c")
set(DSI				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_dsi.c")
set(EXTI				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_exti.c")
set(FLASH			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_flash.c")
set(FLASH_RAMFUNC	"${STDPERIPH_SOURCE_DIR}/stm32f4xx_flash_ramfunc.c")
set(FMC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_fmc.c")
set(FMPI2C			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_fmpi2c.c")
set(FSMC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_fsmc.c")
set(GPIO				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_gpio.c")
set(HASH				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_hash.c")
set(HASH_MD5		"${STDPERIPH_SOURCE_DIR}/stm32f4xx_hash_md5.c")
set(HASH_SHA1		"${STDPERIPH_SOURCE_DIR}/stm32f4xx_hash_sha1.c")
set(I2C				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_i2c.c")
set(IWDG				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_iwdg.c")
set(LPTIM			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_lptim.c")
set(LTDC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_ltdc.c")
set(PWR				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_pwr.c")
set(QSPI				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_qspi.c")
set(RCC				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_rcc.c")
set(RNG				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_rng.c")
set(RTC				${STDPERIPH_SOURCE_DIR}/stm32f4xx_rtc.c)
set(SAI				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_sai.c")
set(SDIO				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_sdio.c")
set(SPIFRX			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_spifrx.c")
set(SPI				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_spi.c")
set(SYSCFG			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_svscfg.c")
set(TIM				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_tim.c")
set(USART			"${STDPERIPH_SOURCE_DIR}/stm32f4xx_usart.c")
set(WWDG				"${STDPERIPH_SOURCE_DIR}/stm32f4xx_wwdg.c")

#set(STDPRIPH_FLAGS "-DUSE_FULL_ASSERT -DUSE_STDPERIPH_DRIVER")
set(STDPRIPH_FLAGS "-DUSE_STDPERIPH_DRIVER")
