message(STATUS "Compilation with CMSIS library")

enable_language(ASM)

if(NOT DEVICE)
    message(FATAL_ERROR "Name of device is not set")
    return()
endif()

if(DEVICE STREQUAL "STM32F407VG")
	set(DEVICE_FAMILY				"cortex-m4")
	set(DEVICE_FREQ				8000000)
	set(DEVICE_FLASH_SIZE		"1M")
	set(DEVICE_RAM_SIZE			"192K")
	set(DEVICE_STACK_ADDRESS	"0x20010000")
	set(DEVICE_FLASH_ORIGIN		"0x08000000")
	set(DEVICE_RAM_ORIGIN		"0x20000000")
	set(DEVICE_LOW_NAME			"STM32F40_41xxx")
	set(DEVICE_FILE_ID			"stm32f4xx")
	set(DEVICE_FULL_NAME			"STM32F407VG")

	set(CMSIS_FLAGS "-D${DEVICE_LOW_NAME} -DHSE_VALUE=${DEVICE_FREQ}")

	#	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D${DEVICE_LOW_NAME} -DHSE_VALUE=${DEVICE_FREQ}")
	#	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D${DEVICE_LOW_NAME} -DHSE_VALUE=${DEVICE_FREQ}")
endif()

set(CMSIS_ROOT_DIR		"${CMAKE_CURRENT_LIST_DIR}/cmsis")
set(CMSIS_INCLUDE_DIR	"${CMSIS_ROOT_DIR}/include")
set(CMSIS_SOURCE_DIR 	"${CMSIS_ROOT_DIR}/src")
set(CMSIS_TEMPLATE_DIR	"${CMSIS_ROOT_DIR}/tmpl")

set(CMSIS_SYSTEM_SOURCE "${CMSIS_SOURCE_DIR}/system_${DEVICE_FILE_ID}.c")

if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/src)
	file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/src)
endif()

if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/include/${DEVICE_FILE_ID}_it.h)
    file(COPY "${CMSIS_TEMPLATE_DIR}/${DEVICE_FILE_ID}_it.h" DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/include)
endif()
if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/src/${DEVICE_FILE_ID}_it.c)
    file(COPY "${CMSIS_TEMPLATE_DIR}/${DEVICE_FILE_ID}_it.c" DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/src)
endif()

#set(CMSIS_HANDLERS_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/stm32f4xx_it.h")
#set(CMSIS_HANDLERS_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/stm32f4xx_it.c")

set(CMSIS_SYSTEM_HEADER "${CMSIS_INCLUDE_DIR}/system_${DEVICE_FILE_ID}.h")
set(CMSIS_DEVICE_HEADER "${CMSIS_INCLUDE_DIR}/${DEVICE_FILE_ID}.h")

if(ARM_NONE_EABI_GCC)
    set(CMSIS_STARTUP_FILE "${CMSIS_SOURCE_DIR}/startup_${DEVICE_FILE_ID}.s")
elseif()
    message(WARNING "Startup family can't be specifyed")
endif()

set(CMSIS_SOURCES ${CMSIS_SYSTEM_HEADER} ${CMSIS_SYSTEM_SOURCE} ${CMSIS_DEVICE_HEADER} ${CMSIS_STARTUP_FILE})

set(DEVICE_LINKER_SCRIPT "${CMSIS_ROOT_DIR}/stm32_flash.ld.in")

configure_file(${DEVICE_LINKER_SCRIPT} ${CMAKE_CURRENT_BINARY_DIR}/stm32_flash.ld)
set(CMSIS_LINKER_FLAGS "-T${CMAKE_CURRENT_BINARY_DIR}/stm32_flash.ld")
